import type { Metadata } from "next";
import PaginationElems from "../src/components/paginationElements/PaginationElems";
import ReduxProvider from "./provider/Provider";
import ContextForAppClient from "./ContextForApp";
import TSectionElement from "../src/components/topSection/TSectionElement/TSectionElement";
import BottomPanel from "../src/components/bottomPanel/BottomPanel";
import AroundMain from "../src/components/AroundMain/AroundMain";
import "./index.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <ContextForAppClient>
        <html lang="en">
          <body>
            <AroundMain>
              <TSectionElement />
              <main>{children}</main>
              <PaginationElems />
              <BottomPanel />
            </AroundMain>
          </body>
        </html>
      </ContextForAppClient>
    </ReduxProvider>
  );
}
